### ISSUE TITLE
Need a setting for file patterns

### ISSUE THREAD

**Issue by anikitin** [tylerlong/vscode-openapi-linter#1]
I can have many different YaML and JSON files in my workspace, I want to apply linter only to ones satisfying the mask. See example from original Spectral VS Code plugin:

"spectral.validateFiles": [
  "*/**/*-openapi.yml",
  "**/*-openapi.json"
]

![image](https://user-images.githubusercontent.com/1359781/161891940-6cdf705f-7d91-431b-8a9e-baebfc95e7e9.png)

**Comment by tylerlong** [comment]
Supported in version 0.2.5

**Comment by tylerlong** [comment]
JSON specs are supported as well. But by default JSON support is not enabled. You need to enable it by adding `**/my-spec.json` to `openApiLinter.validateFiles` of settings.json
