### ISSUE TITLE
UX for settings

### ISSUE THREAD

**Issue by anikitin** [tylerlong/vscode-openapi-linter#2]
Would be really nice to have UI for settings like in original Spectral VS Code plugin:

![image](https://user-images.githubusercontent.com/1359781/161892077-5315b64a-4e94-4fd7-b7ce-26ce384aa560.png)

**Comment by tylerlong** [comment]
![Screen Shot 2022-04-08 at 11 44 59 AM](https://user-images.githubusercontent.com/733544/162502733-0b2d7c3e-3ede-4bad-8654-0b819df96b2e.png)

Supported in version 0.2.3. But for now there is only one setting.

**Comment by tylerlong** [comment]
0.2.4 added one more setting item:

![Screen Shot 2022-04-08 at 2 28 53 PM](https://user-images.githubusercontent.com/733544/162534663-e83df110-0819-45c5-af08-8727f0b97bb2.png)
