### ISSUE TITLE
References to external fragments via $ref are not properly supported

### ISSUE THREAD

**Issue by anikitin** [tylerlong/vscode-openapi-linter#3]
See attached files: if they are placed in the subdirectory within a workspace, it causes error.
In my case both files are inside openapi/test directory while linter searches the referred file in workspace root.

 
[ref-issue.zip](https://github.com/ringcentral/vscode-openapi-linter/files/8423471/ref-issue.zip)

![image](https://user-images.githubusercontent.com/1359781/161892689-4e6df268-c998-4fbc-a865-4fcd683a0562.png)

**Comment by tylerlong** [comment]
I cannot reproduce the issue. It doesn't tell me that it cannot find the file.

![Screen Shot 2022-04-14 at 11 21 51 AM](https://user-images.githubusercontent.com/733544/163453080-8197be5b-bff8-4305-8583-e1734930df85.png)

**Comment by anikitin** [comment]
See https://www.loom.com/share/122bdea1e5f24aca92985f5af163e79e

**Comment by tylerlong** [comment]
Fixed, please try version 0.3.0
