### ISSUE TITLE
External spectral rules file is not applied

### ISSUE THREAD

**Issue by anikitin** [tylerlong/vscode-openapi-linter#5]
Windows 10
When I specify external Spectral rules file it doesn't seem to be applied. Linter uses default rules.
No issues noticed in log output.

See https://www.loom.com/share/122bdea1e5f24aca92985f5af163e79

Source is here
[vs-plugin-issues.zip](https://github.com/ringcentral/vscode-openapi-linter/files/8491983/vs-plugin-issues.zip)

**Comment by tylerlong** [comment]
Fixed. regression bug when adding new features. https://github.com/ringcentral/vscode-openapi-linter/compare/ca804d710ec665481938afad29282218dd036d8e...main
