### ISSUE TITLE
Package for other editors

### ISSUE THREAD

**Issue by williamboman** [tylerlong/vscode-openapi-linter#8]
Hey! I ended up here after finding out that the "official" Spectral VSCode extension is unmaintained, and this seems a bit more active. I was wondering if you have considered packaging this for other LSP capable editors? There are a few alternatives to this, for example publishing it as a standalone npm package, or even just publishing the `.vsix` archives as assets in GitHub releases.

**Comment by tylerlong** [comment]
I can publish the `.vsix` for sure. How hard is it for other editors to use the `.vsix`?

**Comment by tylerlong** [comment]
https://github.com/ringcentral/vscode-openapi-linter/releases/tag/0.3.4

**Comment by williamboman** [comment]
That works! It's just a zip archive at the end of the day, so installation is pretty trivial :)
